# Generated by Django 4.2.6 on 2023-11-02 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={},
        ),
    ]
