# Generated by Django 4.2.6 on 2023-11-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_grade_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='year',
        ),
        migrations.AddField(
            model_name='grade',
            name='gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='grade',
            table=None,
        ),
    ]
